// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcepxnjdvsgxsraaxcyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjZXB4bmpkdnNneHNyYWF4Y3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDgzNDAsImV4cCI6MjA2OTMyNDM0MH0.LglTu4WZWdKZztGZOSwFGq8M2NVfnBU_3i5MotkqiwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});